######################################################################
# Automatically generated by qmake (3.0) Thu Aug 21 18:46:21 2014
######################################################################

TEMPLATE = app
TARGET = CutImage
INCLUDEPATH += .

# Input
HEADERS += CutImage.h
SOURCES += CutImage.cpp main.cpp
