#############################################################################
# Makefile for building: CutImage.app/Contents/MacOS/CutImage
# Generated by qmake (3.0) (Qt 5.3.1)
# Project:  CutImage.pro
# Template: app
# Command: /Applications/Qt5.3.1/5.3/clang_64/bin/qmake -o Makefile CutImage.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I/Applications/Qt5.3.1/5.3/clang_64/mkspecs/macx-clang -I. -I. -I/Applications/Qt5.3.1/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers -I/Applications/Qt5.3.1/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/System/Library/Frameworks/AGL.framework/Headers -F/Applications/Qt5.3.1/5.3/clang_64/lib
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.6
LIBS          = $(SUBLIBS) -F/Applications/Qt5.3.1/5.3/clang_64/lib -framework QtGui -framework QtCore -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
QMAKE         = /Applications/Qt5.3.1/5.3/clang_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = CutImage.cpp \
		main.cpp 
OBJECTS       = CutImage.o \
		main.o
DIST          = /Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/spec_pre.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/qdevice.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/device_config.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/common/shell-unix.conf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/common/unix.conf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/common/mac.conf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/common/macx.conf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/common/gcc-base.conf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/common/clang.conf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/common/clang-mac.conf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/qconfig.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/qt_functions.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/qt_config.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/macx-clang/qmake.conf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/spec_post.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/exclusive_builds.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/default_pre.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/mac/default_pre.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/resolve_config.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/default_post.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/mac/sdk.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/mac/default_post.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/mac/objective_c.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/warn_on.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/qt.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/resources.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/moc.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/unix/opengl.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/unix/thread.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/mac/rez.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/testcase_targets.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/exceptions.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/yacc.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/lex.prf \
		CutImage.pro CutImage.cpp \
		main.cpp
QMAKE_TARGET  = CutImage
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = CutImage.app/Contents/MacOS/CutImage

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk \
		-mmacosx-version-min=10.6 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile CutImage.app/Contents/PkgInfo CutImage.app/Contents/Resources/empty.lproj CutImage.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@test -d CutImage.app/Contents/MacOS/ || mkdir -p CutImage.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: CutImage.pro /Applications/Qt5.3.1/5.3/clang_64/mkspecs/macx-clang/qmake.conf /Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/spec_pre.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/qdevice.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/device_config.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/common/shell-unix.conf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/common/unix.conf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/common/mac.conf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/common/macx.conf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/common/gcc-base.conf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/common/clang.conf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/common/clang-mac.conf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/qconfig.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/qt_functions.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/qt_config.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/macx-clang/qmake.conf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/spec_post.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/exclusive_builds.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/default_pre.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/mac/default_pre.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/resolve_config.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/default_post.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/mac/sdk.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/mac/default_post.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/mac/objective_c.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/warn_on.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/qt.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/resources.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/moc.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/unix/opengl.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/unix/thread.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/mac/rez.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/testcase_targets.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/exceptions.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/yacc.prf \
		/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/lex.prf \
		CutImage.pro \
		/Applications/Qt5.3.1/5.3/clang_64/lib/QtGui.framework/QtGui.prl \
		/Applications/Qt5.3.1/5.3/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile CutImage.pro
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/spec_pre.prf:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/qdevice.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/device_config.prf:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/common/shell-unix.conf:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/common/unix.conf:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/common/mac.conf:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/common/macx.conf:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/common/gcc-base.conf:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/common/gcc-base-mac.conf:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/common/clang.conf:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/common/clang-mac.conf:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/qconfig.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_core.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_help.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_network.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_script.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/qt_functions.prf:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/qt_config.prf:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/macx-clang/qmake.conf:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/spec_post.prf:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/exclusive_builds.prf:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/default_pre.prf:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/mac/default_pre.prf:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/resolve_config.prf:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/default_post.prf:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/mac/sdk.prf:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/mac/default_post.prf:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/mac/objective_c.prf:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/warn_on.prf:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/qt.prf:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/resources.prf:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/moc.prf:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/unix/opengl.prf:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/unix/thread.prf:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/mac/rez.prf:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/testcase_targets.prf:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/exceptions.prf:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/yacc.prf:
/Applications/Qt5.3.1/5.3/clang_64/mkspecs/features/lex.prf:
CutImage.pro:
/Applications/Qt5.3.1/5.3/clang_64/lib/QtGui.framework/QtGui.prl:
/Applications/Qt5.3.1/5.3/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile CutImage.pro

qmake_all: FORCE

CutImage.app/Contents/PkgInfo: 
	@test -d CutImage.app/Contents || mkdir -p CutImage.app/Contents
	@$(DEL_FILE) CutImage.app/Contents/PkgInfo
	@echo "APPL????" >CutImage.app/Contents/PkgInfo
CutImage.app/Contents/Resources/empty.lproj: 
	@test -d CutImage.app/Contents/Resources || mkdir -p CutImage.app/Contents/Resources
	@touch CutImage.app/Contents/Resources/empty.lproj
	
CutImage.app/Contents/Info.plist: 
	@test -d CutImage.app/Contents || mkdir -p CutImage.app/Contents
	@$(DEL_FILE) CutImage.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@BUNDLEIDENTIFIER@,com.samapp.CutImage,g" -e "s,@EXECUTABLE@,CutImage,g" -e "s,@TYPEINFO@,????,g" /Applications/Qt5.3.1/5.3/clang_64/mkspecs/macx-clang/Info.plist.app >CutImage.app/Contents/Info.plist
dist: 
	@test -d .tmp/CutImage1.0.0 || mkdir -p .tmp/CutImage1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/CutImage1.0.0/ && $(COPY_FILE) --parents CutImage.h .tmp/CutImage1.0.0/ && $(COPY_FILE) --parents CutImage.cpp main.cpp .tmp/CutImage1.0.0/ && (cd `dirname .tmp/CutImage1.0.0` && $(TAR) CutImage1.0.0.tar CutImage1.0.0 && $(COMPRESS) CutImage1.0.0.tar) && $(MOVE) `dirname .tmp/CutImage1.0.0`/CutImage1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/CutImage1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r CutImage.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

CutImage.o: CutImage.cpp CutImage.h \
		/Applications/Qt5.3.1/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QImage \
		/Applications/Qt5.3.1/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qimage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CutImage.o CutImage.cpp

main.o: main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

